const ActionTypes = {
  IS_SIGN_LODER: "IS_SIGN_LODER",
  IS_REGISTER_ERROR:"IS_REGISTER_ERROR",
  PARKING_LIST:"PARKING_LIST",
  PARKING_ID:"PARKING_ID",
  SLOTS_:"SLOTS_",
  SELECTED_DATA:"SELECTED_DATA",
  MY_SLOTS:"MY_SLOTS",
  AREA_NAME:"AREA_NAME",
  DELETE_SLOT:"DELETE_SLOT",
  DELETE_BOOKINGs:"DELETE_BOOKINGs",
  EMPTY_PARKING_LIST:"EMPTY_PARKING_LIST",
  EMPTY_PARKING_SELECT:"EMPTY_PARKING_SELECT",
  CURRENT_USER:"CURRENT_USER",
  ALL_BOOKING:"ALL_BOOKING",
  USER_LIST:"USER_LIST",
  EMPTY_STATE:"EMPTY_STATE",
  PARKING_TIME:"PARKING_TIME",
  EMPTY_ALL_BOOKING_LIST:"EMPTY_ALL_BOOKING_LIST",
  DELETE_USER:"DELETE_USER",
  EMPTY_USER_LIST:"EMPTY_USER_LIST",
  PARKING_TIME_EMPTY:"PARKING_TIME_EMPTY"
  

}

export default ActionTypes